### ISSUE TITLE
Creating instances having a public interface without ip addresses isn't possible

### ISSUE THREAD

**Issue by eliobischof** [cloudscale-ch/cloudscale-go-sdk#23]
I'm trying to use a floating IP without assigning each instance candidate an additional own external IP. I guess floating IPs can only be assigned to instances having a public network interface, can't they? So, is it possible to create instances having a public interface without addresses?

The following code panics with `detail: It is not possible to define interfaces and use_public_interface.`

```golang
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/cloudscale-ch/cloudscale-go-sdk"
)

func main() {

	client := cloudscale.NewClient(&http.Client{
		Timeout: 60 * time.Second,
	})

	client.AuthToken = os.Getenv("CLOUDSCALE_TOKEN")

	ctx := context.Background()

	createServer(ctx, client)
}

func createServer(ctx context.Context, client *cloudscale.Client) {
	_, err := client.Servers.Create(ctx, &cloudscale.ServerRequest{
		ZonalResourceRequest:  cloudscale.ZonalResourceRequest{},
		TaggedResourceRequest: cloudscale.TaggedResourceRequest{},
		Name:                  "elio-ip-less-public-iface",
		Flavor:                "flex-2",
		Image:                 "centos-7",
		Zone:                  "lpg1",
		VolumeSizeGB:          30,
		Volumes:               nil,
		Interfaces: &[]cloudscale.InterfaceRequest{{
			Network:   "public",
			Addresses: &[]cloudscale.AddressRequest{},
		}},
		BulkVolumeSizeGB:  0,
		SSHKeys:           []string{"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcetfGsOPJ/EzGBE/iiLfot43Ihyd44RFrmW0ORvPMiCk09Vrxf8vCSWrnXSpokBfIiKW43WPs6hHjzw9VWHwmV1JmSlpcKrUUhq5hKl78j3IglTdKw5fd89BMpNZa+pROcxeq0txiR7t+yYf5NdjHix1mVle/MosyaMzPOO5Cpgb8v8wmniFuIPyhVwz/q31LEbL8SunuuMXrufFdV7QX5rki8hPN2exQ20yUeJLy+eBHUnE52icyi4fXT/OfehWI28IIJ82efN2ddUc4tbwd5M7BbfL4ezHLM7/b+OS/eD+FnNWhfwrZKxUslsF4oEi2ynVY5EgvPGv5ibRiwCGLt8oC2RvrLZzgUlBgHeB7zqcN8DNDLqeqd4BCKps5AQrQvhLiw9CMS7p88mhjJhipDKCGDp/kYDefTb0G79gzmD4rmrCO/H4wk7cBLqZacJ0C61WzA9isSZSmymNG+CzUp4SPuVLmbt4eWeUnF8w4cPGF+RhpQGHs9Rwvto+hXuW8jJ8ERKcc/aLWyhMsp9FvL4SP+3U6ax+PfneBm0KWzfzd9M4TJRCAeyr7N8OHmjiauHQ/ws4LWvYWh31In8cuPXbVZTsYxOViXaN1vp4/6L4TTzMp/mDQ4n+D5zG1m2beMc5nmre6pp14K77Iwo07kBu1jb5Fu78qUCst4CiiXQ== elio@caos.com"},
		Password:          "",
		UsePublicNetwork:  boolPtr(false),
		UsePrivateNetwork: boolPtr(true),
		UseIPV6:           boolPtr(false),
		AntiAffinityWith:  "",
		ServerGroups:      nil,
		UserData:          "",
	})
	if err != nil {
		panic(err)
	}
}
```

**Comment by alakae** [comment]
Hi

Thank you for your questions! Unfortunately, this is not possible. Floating IPs only work in combination with servers having an IP address of the same IP version. Similarly, public interfaces are only allowed in combination with at least an IPv4 address (IPv6 is optional).

Looking at your code snippet I have noticed two things:

 * It's not possible to use the `UsePublicNetwork`/`UsePrivateNetwork` and `Interfaces` properties simultaneously. The bool properties are for convenience, whereas the `Interfaces` allows advanced networking setups. This is what's causing the `detail: It is not possible to define interfaces and use_public_interface.` error message.

 * As mentioned above, it's not possible to have a public network interface and no addresses. When you use `Network: "public"` in an `InterfaceRequest` no other options should be added.

Some more information can be found at: https://www.cloudscale.ch/en/api/v1#interfaces-attribute-specification

I hope this information is useful to you. If you have additional questions, please feel free to reach out to us again.

Alain
