### ISSUE TITLE
Volume missing in ServerRequest

### ISSUE THREAD

**Issue by splattner** [cloudscale-ch/cloudscale-go-sdk#7]
https://github.com/cloudscale-ch/cloudscale-go-sdk/blob/master/servers.go#L74

ServerRequest should include `volumes`, see API https://www.cloudscale.ch/en/api/v1#servers-create

**Comment by davidhalter** [comment]
Created a ticket internally as well for this. Please let us know how important this is to you.

**Comment by davidhalter** [comment]
Alain wrote a fix for this. Please let us know if it works.
